### PR TITLE
Fix price calculation for non-reducible ingredients with modified res…

### LINKED ISSUE #38: AU3 is more expensive than AU2?
Granted, I'm using resource modifier = 0.5 but that should not mean you need half an au2 to make an au3
image

### PR DESCRIPTION
**Pull request by aritchie05**
…ourceCostMultiplier

Resolves #38

### CODE REVIEW

**Comment by rannmann** [comment]
Does the modifier also affect the work input?  I noticed the price goes *slightly* down with the modifier set to 0.5 now, and it seems to be calorie-cost-related.

**Comment by aritchie05** [comment]
> Is the modifier supposed to affect the work input? I noticed the price goes _slightly_ down with the modifier set to 0.5 now, and it seems to be calorie-cost-related.

I am not exactly following. A quick test seems to show craft resource modifier having no effect on calorie cost.

100x modifier:
image

0.1x modifier:
image

**Comment by rannmann** [comment]
Default modifier (1):
image

Modifier = 0.5:
image

**Comment by aritchie05** [comment]
Hmm that is strange. It only seems to apply when the ingredient cost is non-zero. If you set all the ingredient costs to zero, and just leave the calorie cost, changing the craft resource modifier has no effect. Need to investigate more.

**Comment by aritchie05** [comment]
@rannmann are you testing on currently deployed environment or with the Preview for this PR?

**Comment by rannmann** [comment]
> @rannmann are you testing on currently deployed environment or with the Preview for this PR?

I was using the preview for this PR.

**Comment by aritchie05** [comment]
> > @rannmann are you testing on currently deployed environment or with the Preview for this PR?
> 
> I was using the preview for this PR.

I looked at this quite a bit until I came to a realization. Changing the craft resource modifier SHOULD actually increase the price of an AU3 somewhat, given that the ingredients (iron bar, nail) are in the outputs section. This is because those outputs have a nonzero price (e.g. 0.01). When craft resource modifier is increased, the number of that ingredient (e.g. Iron Bar) required for the AU3 recipe goes up. So the price should go up slightly.

**Comment by rannmann** [comment]
Ah right, that makes sense.

**Pull request merged**
