### PR TITLE
Update dependencies including Angular v17

### PR DESCRIPTION
**Pull request by vdbongard**
Hey, thank you for the tool! I have looked at the code a bit and updated the Angular version to 17 and updated the other dependencies also. Please have a look.

### CODE REVIEW

**Comment by lifezoned4** [comment]
Nice work will check this out too! <3

**Comment by lifezoned4** [comment]
How about put in a .tool-versions (e.g. support for [asdf](https://github.com/asdf-vm/asdf)) to pin the nodejs version. Would make some life easier.

**Comment by lifezoned4** [comment]
Sadly this version has the render glitch in chrome too. Will put up a issue for this. Hoped to have this fixed with it 😞

**Comment by lifezoned4** [comment]
@vdbongard should I try to fix CI or will you do?

**Comment by aritchie05** [comment]
Hi @vdbongard I got this error when I tried to run the deploy on Vercel with Node.js 20.9.0

Error: Schema validation failed with the following errors:
--
16:10:50.103 | Data path "" must NOT have additional properties(extractCss).
16:10:50.147 | /vercel/path0/node_modules/rxjs/dist/cjs/internal/util/reportUnhandledError.js:13
16:10:50.148 | throw err;
16:10:50.148 | ^
16:10:50.148 |  
16:10:50.148 | SchemaValidationException [Error]: Schema validation failed with the following errors:
16:10:50.148 | Data path "" must NOT have additional properties(extractCss).
16:10:50.148 | at /vercel/path0/node_modules/@angular-devkit/architect/src/architect.js:40:27 {
16:10:50.148 | errors: [
16:10:50.148 | {
16:10:50.149 | instancePath: '',
16:10:50.149 | schemaPath: '#/additionalProperties',
16:10:50.149 | keyword: 'additionalProperties',
16:10:50.149 | params: { additionalProperty: 'extractCss' },
16:10:50.149 | message: 'must NOT have additional properties'
16:10:50.149 | }
16:10:50.150 | ]
16:10:50.150 | }
16:10:50.150 |  
16:10:50.150 | Node.js v20.9.0
16:10:50.179 | Error: Command "ng build --configuration=$ENVIRONMENT" exited with 1

**Comment by vdbongard** [comment]
Ah I could reproduce it locally with `ng build --configuration=production`.
I have updated the angular.json similarly to a newly created Angular application (`ng new`).
This error is fixed now and it also uses the new and faster application builder which uses esbuild (instead of webpack) under the hood.

**Pull request merged**
